### ISSUE TITLE
[r518] Unity works slower with themes than without

### ISSUE THREAD

**Issue by darkhog** [zios/unity-themes#10]
Or slower than in older version of Zios for that matter. Could you please do something about that? Switching into play mode is particularly slow on my machine. If you are unable to repro this on your side, we could arrange a TeamViewer session so you can try on my side.

**Comment by bradsmithee** [comment]
Run-time performance should only be effected by the frequency of render refreshes (for hover effects).  At a value of none, it should function practically the same as stock.  That said, yes, startup performance (which is re-triggered on entering play mode) is a bit slower.  It shouldn't be too much more as I did tighten it the best I could, but I'll try to offer a few options in the next version to disable playmode loading of themes for users who frequently switch.

**Comment by darkhog** [comment]
Hm, couldn't you put runtime loading into a coroutine and load it over few frames? Slow loading would be preferable to hang up.

Also it's not just playmode, it's just most egregious slowdown. Another thing, much smaller I admit, is when selecting objects in inspector, have to wait a second or two for inspector to update where in previous version and w/out theming it is instant.

**Comment by darkhog** [comment]
Sorry, but even when Hover Response is set to none, it works much slower than stock. Maybe check cursor position every frame and only redraw components that are reasonably close to it instead of everything? Haven't dabbled in `OnGUI()` stuff in a while (since ugui came along) but should be possible and should make it faster.

Finally, instead of managed DLL, could you make it so releases contains directory structure with Editor folders and regular CS files? So if I see any bug that I think I could fix I can just edit them without downloading potentially broken GIT version?

**Comment by bradsmithee** [comment]
> Hm, couldn't you put runtime loading into a coroutine and load it over few frames? Slow loading would be preferable to hang up.
I wouldn't really be able to split up the update/per-frame runtime as it's just a single, delayed global repaint.  I'd love to split the initialization/startup time into a separate thread, but as you are probably aware, Unity does not play nicely with that concept while using its mechanisms. 

Yes, I could chunk the startup into stepped passes/a coroutine to spread the load evenly over a few frames.  I'll need to re-profile a few load methods and isolate problem areas for that.  Last I tested and fine-tuned performance, however, there was only a minuscule difference in terms of entering play mode (~1-2 seconds).  I may need to bench/test lower-end machines.  Out of curiosity, is your project on a SSD?  What is your CPU?

> Also it's not just playmode, it's just most egregious slowdown. Another thing, much smaller I admit, is when selecting objects in inspector, have to wait a second or two for inspector to update where in previous version and w/out theming it is instant.
What you are describing sounds like very early, unoptimized versions of the theme system (well before releases were made).  Quite odd.  I do not think I have _ever_ had any performance hiccups while selecting objects though.

> Sorry, but even when Hover Response is set to none, it works much slower than stock.
Stock doesn't have a hover response at all on editor elements, so it could not possibly be faster on displaying that particular effect.  It has a semi-reliable 1-2 second tooltip response, but that's about it.

> Maybe check cursor position every frame and only redraw components that are reasonably close to it instead of everything? Haven't dabbled in OnGUI() stuff in a while (since ugui came along) but should be possible and should make it faster.
While hover response is not set to none, cursor position is compared every frame and redraws only happen on changes.  Isolating only select editor windows to redraw was planned at one point, but as my test machine has no notable difference in performance, I did not pursue it further.  The system mostly works in broad strokes without knowing or catering to specific editor window types -- such as making per "component" redraws for the default inspector.

> Finally, instead of managed DLL, could you make it so releases contains directory structure with Editor folders and regular CS files? So if I see any bug that I think I could fix I can just edit them without downloading potentially broken GIT version?
That seems counter-intuitive to releases. The releases are supposed to easily digestible, packaged, ready to go versions of the project.  If you check out the GIT version/files corresponding to the release (which should already be downloadable in the releases page anyhow under the main zip), they are usable editor folders with regular .cs files.  Having Codebase and Themes in your project should be what you want.

---------

Can you prepare me a zip of a sample project in question with sluggish performance so I can test/recreate it locally?  Just a sample scene and hierarchy with whatever addons/extensions you use should do nicely.

**Comment by bradsmithee** [comment]
Fixed in [latest release](https://github.com/zios/unity-themes/releases/tag/r549).
