### ISSUE TITLE
Cannot open child folder/objects

### ISSUE THREAD

**Issue by erherhh4herh** [zios/unity-themes#13]
As you can see in the screenshot, my little arrows are inside of the text! Clicking to the side where they normally are does nothing, so does double clicking.

Screenshots:
http://i.imgur.com/AmTFN44.png
http://i.imgur.com/TA4B5Vg.png

Please help! Thanks!!!!!

**Comment by bradsmithee** [comment]
I remember this issue existing long ago, but I'd swore it was resolved. 
 Any console errors?  What version of Unity are you on?

**Comment by seieibob** [comment]
I get this and the same errors as #14. I'm on OSX Sierra with Unity 5.5.

**Comment by bradsmithee** [comment]
Right.  Unity 5.5 is definitely not supported (yet) due to some missing styles.

**Comment by bradsmithee** [comment]
Resolved in [Unity 5.5 Hotfix](https://github.com/zios/unity-themes/releases/tag/r522).
