### ISSUE TITLE
Cannot change theme

### ISSUE THREAD

**Issue by t0msk** [zios/unity-themes#17]
Hello,

I dont have a option `Edit > Preferences > Themes`, is it only for Pro?

Unity3D version: 5.5.2f1

**Comment by bradsmithee** [comment]
Zios Themes are built for Personal, but should work on any edition (although Pro has not been tested).
I see you are using 5.5.2 (which a release zip does not exist for yet).  Have you tested the 5.5.1 release zip?  Did you extract it to your project's Assets folder?

**Comment by bradsmithee** [comment]
5.5.2 support in latest [release](https://github.com/zios/unity-themes/releases/tag/r573)

**Comment by JorgeVV** [comment]
Same problem. r573 did not work for me.
Unity 5.5.2f1 Personal. Windows 7 64bits

**Comment by bradsmithee** [comment]
Likewise with the MacOS issue, the dll was not marked as editor-only.  Fixed in updated [r573](https://github.com/zios/unity-themes/releases/tag/r573).
