### ISSUE TITLE
Problem with case sensitivity in file names

### ISSUE THREAD

**Issue by mysticfall** [zios/unity-themes#18]
Some of the iconsets use inconsistent cases in file names which leads to runtime errors on non Windows platforms, i.e.
```@Themes/Iconsets/Simplicity/UnityEditor.Toolbar.s_CollabIcons.guicontent``` where it should be ```UnityEditor.Toolbar.s_CollabIcons.guiContent``` instead.

**Comment by bradsmithee** [comment]
Thanks for the catch on the inconsistent file names.  I'll patch those up in the next release.  However, it is odd that you are getting runtime errors.  The system relies on a custom, internal FileManager class which *should* perform case-insensitive path/file searches.

**Comment by mysticfall** [comment]
Sorry, should have copied the stacktrace when it happened. It only occurred when I ran some test cases (Unity Tests) in play mode and it kept spamming the message after that, but I'm not too sure if it will also happen with other situation.

But anyway, it went away after I manually changed the file names. Thanks for the quick response!

**Comment by bradsmithee** [comment]
Fixed in latest [release](https://github.com/zios/unity-themes/releases/tag/r573).
