### ISSUE TITLE
No component icon in Simplicity

### ISSUE THREAD

**Issue by mic-code** [zios/unity-themes#23]
Invisible enable icon makes it unusable

![1](https://cloud.githubusercontent.com/assets/26720201/25167459/2a2962c0-2512-11e7-827d-192db88cb36e.png)
![2](https://cloud.githubusercontent.com/assets/26720201/25167460/2a2c2ba4-2512-11e7-8cc0-b88353acb417.png)

**Comment by bradsmithee** [comment]
Is this a default or custom palette?  The "Header" palette color needs to be semi-transparent to function/display correctly due to how Unity layers this region.

**Comment by mic-code** [comment]
That fixed it, thanks
