### ISSUE TITLE
How to remove it?

### ISSUE THREAD

**Issue by rzfzr** [zios/unity-themes#31]
Any ideas on how to remove it?
I'm running beta 2018.2 and it crashes when I close it, if I delete the folder it crashes when I start the project

**Comment by bradsmithee** [comment]
For a _stable_ project, deleting the folder should be all it takes.  If that does not work, try deleting your Project `Library` folder and letting the asset database / cached script assemblies rebuild.

And yes, 2018 is known to have some issues -- even with the [2017.3](http://blaze.bradsmithee.com/file/bradsmithee/Zios.Themes-r603-Windows-2017.3.1.zip) stopgap release.

**Comment by rzfzr** [comment]
Rebuilding the library did it, should have tried it, thanks.
Yep, had problems before with 2017, just giving up on having a dark theme on Unity, still find a ridiculous choice being pro only...

**Comment by bradsmithee** [comment]
2017.3 should work fine with the link I gave in the last post (which is newer than any of the github releases)
