### ISSUE TITLE
Unity 2019 Compatible?

### ISSUE THREAD

**Issue by valkyrienyanko** [zios/unity-themes#40]
Is this compatible with `2019.3.11f1`?

**Comment by bradsmithee** [comment]
At this time, functionality only extends to 2017 (using the attached forum quick-fix).  Later versions of Unity radically changed many things that would require re-works.  There was little interest from users in the project/concept, so I did not continue development to support these versions.

**Comment by valkyrienyanko** [comment]
Okay thankyou.
