### ISSUE TITLE
Please include README.MD in the repo

### ISSUE THREAD

**Issue by Skybladev2** [zios/unity-themes#5]
The essential thing is the Usage section. Not everyone knows about [Unity forums thread](http://forum.unity3d.com/threads/zios-editor-theme-support.411818/).

**Comment by bradsmithee** [comment]
The initial repository was a mirrored sync from the core SVN.  This did not allow extraneous files to exist that were not on both.  The git repository has since been revised to a manual/normal setup.  A readme file is being written/formatted based on the thread's contents now.

**Comment by zios** [comment]
Shortened version of Wiki/Unity thread added as README.MD.
