### ISSUE TITLE
Inspector Animator Transition extends only half of the window width

### ISSUE THREAD

**Issue by Tayx94** [zios/unity-themes#6]
Aweseome idea! I know it's still in development, but I noticed this:

![image](https://cloud.githubusercontent.com/assets/16625646/16362613/13953478-3bb4-11e6-8a8a-27514c47f790.png)
Is it possible to fix this?

**Comment by bradsmithee** [comment]
I'll look into getting the missing elements styled (and fixing the fixed width issue).   What type of asset/window is the inspector targeting?  If it's an asset, could you possibly include a simple zip with what I'll need to view the problem?

**Comment by bradsmithee** [comment]
Fixed (ControlLabel stretchwidth) as well as styled MeTransition elements.
